service: mailer

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  environment:
    SENDGRID_KEY: <Sendgrid API key goes here>
    MAILGUN_DOMAIN: <Mailgun domain goes here>
    MAILGUN_KEY: <Mailgun API key goes here>

functions:
  sendMail:
    handler: mailer.send
    events:
      - http:
          path: mailer/send
          method: post
