service: mailer

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  sendMail:
    handler: mailer.send
    events:
      - http:
          path: mailer/send
          method: post
